---
title: "ETC5521 Assignment 1"
subtitle: "Your title"
team: [FILL]
author:
  - [Aphiaut Imuan]
  - [FILL]
date: "`r Sys.Date()`"
output: 
  html_document
---

[This assignment is for ETC5521 Assignment 1 by Team `r rmarkdown::metadata$team` comprising of `r knitr::combine_words(rmarkdown::metadata$author)`.]{style="color:#006DAE;"}

```{r}
investment <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-10/investment.csv')
chain_investment <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-10/chain_investment.csv')
ipd <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-10/ipd.csv')

```


# Introduction and motivation

[FILL] Give the bigger picture of the data, and inspire the reader to learn more about the problem by reading your analysis. 

Infrastructure investment is an important core of the country. It includes federal investments such as water suppliers and a private sector investment that manages electricity. It also includes the cost of research and development in technology.

Moreover, infrastructure investment plays a role in supporting both businesses and households. For example, the development of logistics has resulted in businesses reducing transportation costs. Households can access infrastructure services and can choose to use them. It also has a positive effect on both short-term and long-term economic growth [(Stupak, 2017)](https://ecommons.cornell.edu/bitstream/handle/1813/78289/CRS_Economic_Impact_of_Infrastructure_Investment_0717.pdf?sequence=1&isAllowed=y).

The above mentioned, the case study of infrastructure should be USA because the USA is a big country, has a large population, and people can access infrastructure services. Furthermore, the USA is also the world's largest economy. 

# Data description

[FILL] Source of the data, and detail the structure of the data

# Questions of interest

[FILL] What questions might be possible to answer with this data, aiming for about 20. Bold the 3-4 questions you will address in the 

1. What category of investment is the highest average gross investment and Chain? Does it same?

2. What is the trend of total basic infrastructure?

3. what is the trend of total social infrastructure?

4. What year and category are the highest investment and Chain?

5. What year and category are the lowest investment and Chain?

**6. What is the relationship between total digital investment and gdp?** (download gdp from other and join it later)

7. What are the highest investment between Air, Water, Rail transportation investment ?

8. What are the similarities/difference of trend between Federal electric power structures investment and Private electric power structures investment?

9. How does the digital investment change? (ipd) it will show the changing of price base on based year (2012)

10. How does the transportation investment change? (ipd) it will show the changing of price base on based year (2012)

11. How does the power investment change? (ipd) it will show the changing of price base on based year (2012)

12. What is the proportion of total social investment in all category infrastructure?

13. What is the proportion of total basic infrastructure investment in all category infrastructure?

14. **How does changing of basic infrastructure investment (million dollar) similar/different with Implicit Price Deflators  (IPDs) of basic infrastructure investment?**

15. What are the trends in all categories infrastructure investment so far?

16. In 2012, what is the proportion of various investments in the total investment？

17. What category of investment has the greatest impact on GDP and how?

18. **What is the relationship between GDP and private investment, federal investment？And which one is stronger impact on GDP?**

19. What is the proportion of total digital investment in all category infrastructure?

20. **Is there a linear relationship between GDP and total basic infrastructure investment? Positive or negative?**

# Expected findings

[FILL] For your chosen questions explain what you think you might find.

In question 6: We expect the positive relationship between total data investment and GDP. Moreover we expect to see the steep line from 1900 to 2017.

In question 14: We expect the results should be the same or slightly difference.

# Analysis and findings

[FILL] Should include at least one plot or numerical summary for each of your questions, that helps the reader arrive at an answer. You should also write paragraphs describing the methods, summaries and findings. 

# References
