% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={ETC5521 Assignment 1},
  pdfauthor={Aphiaut Imuan; Xintong You},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{ETC5521 Assignment 1}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Infrastructural Investment in USA}
\author{Aphiaut Imuan \and Xintong You}
\date{2022-08-26}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
{This assignment is for ETC5521 Assignment 1 by Team lorikeet comprising of Aphiaut Imuan and Xintong You.}

\hypertarget{introduction-and-motivation}{%
\section{Introduction and motivation}\label{introduction-and-motivation}}

Infrastructure investment is an important core of the country. It includes federal investments such as water suppliers and a private sector investment that manages electricity. It also includes the cost of research and development in technology.

Moreover, infrastructure investment plays a role in supporting both businesses and households. For example, the development of logistics has resulted in businesses reducing transportation costs. Households can access infrastructure services and can choose to use them. It also has a positive effect on both short-term and long-term economic growth \href{https://ecommons.cornell.edu/bitstream/handle/1813/78289/CRS_Economic_Impact_of_Infrastructure_Investment_0717.pdf?sequence=1\&isAllowed=y}{(Stupak, 2017)}.

The above mentioned, the case study of infrastructure should be USA because the USA is a big country, has a large population, and people can access infrastructure services. Furthermore, the USA is also the world's largest economy.

\hypertarget{data-description}{%
\section{Data description}\label{data-description}}

The data comes from \href{https://www.bea.gov/system/files/papers/BEA-WP2020-12.pdf}{Bureau of Economic Analysis}. The raw .xlsx file is included, or can be downloaded directly from the \href{https://www.bea.gov/system/files/2021-01/infrastructure-data-may-2020.xlsx}{BEA Working paper series}.

The 3 primary data sets are already cleaned and saved as .csv files and they all have five variables. Of these, the four variables are the same as below.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.1111}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.1111}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.3222}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.4556}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
class
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
description
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
e.g.
\end{minipage} \\
\midrule()
\endhead
category & character & Category of investment & Private,Federal\ldots{} \\
meta\_cat & character & Group category of investment & Total infrastructure,Water supply,GDP\ldots{} \\
group\_num & double & Group number of investment & 1,2,3\ldots{} \\
year & double & Year of investment & 1947,1948,1949\ldots{} \\
\bottomrule()
\end{longtable}

The 3 data sets record the gross investment, chained investment in millions of USD and Implicit Price Deflators (IPDs) respectively.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.0678}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.0297}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.9025}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
class
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
description
\end{minipage} \\
\midrule()
\endhead
gross\_inv & double & Gross investment in millions of USD \\
gross\_inv\_chain & double & Gross investment (chained 2021 dollars) in millions of USD \\
gross\_inv\_ipd & double & Implicit Price Deflators (IPDs) An implicit price deflator is the ratio of the current-dollar value of a series, such as gross domestic product (GDP), to its corresponding chained-dollar value, multiplied by 100. \\
\bottomrule()
\end{longtable}

The gdplev data set is downloaded from \href{https://www.bea.gov/data/gdp/gross-domestic-product}{Bureau of Economic Analysis}, which is a supplementary data set for our analysis. It records the current GDP and chain GDP in US from 1929 to 2021. Its variable contains year, GDP\_current and GDP\_chain whose type is all double.

\begin{itemize}
\tightlist
\item
  Chained dollars: Chained dollars is a method of adjusting real dollar amounts for inflation over time, to allow the comparison of figures from different years. The U.S. Department of Commerce introduced the chained-dollar measure in 1996.
\end{itemize}

\hypertarget{questions-of-interest}{%
\section{Questions of interest}\label{questions-of-interest}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  What category of investment is the highest average gross investment and Chain? Does it same?
\item
  What is the trend of total basic infrastructure?
\item
  what is the trend of total social infrastructure?
\item
  What year and category are the highest investment and Chain?
\item
  What year and category are the lowest investment and Chain?
\item
  \textbf{What is the relationship between total digital investment and GDP?}
\item
  What are the highest investment between Air, Water, Rail transportation investment ?
\item
  What are the similarities/difference of trend between Federal electric power structures investment and Private electric power structures investment?
\item
  How does the digital investment change?
\item
  How does the transportation investment change?
\item
  How does the power investment change?
\item
  What is the proportion of total social investment in all category infrastructure?
\item
  What is the proportion of total basic infrastructure investment in all category infrastructure?
\item
  \textbf{What is the relationship between transportation investment (chained US dollars) and GDP (chained US dollars)?}
\item
  What are the trends in all categories infrastructure investment so far?
\item
  In 2012, what is the proportion of various investments in the total investment？
\item
  What category of investment has the greatest impact on GDP and how?
\item
  \textbf{What is the relationship between GDP and private investment, federal investment？And which one is stronger impact on GDP?}
\item
  What is the proportion of total digital investment in all category infrastructure?
\item
  \textbf{Is there a linear relationship between GDP and total basic infrastructure investment? Positive or negative?}
\end{enumerate}

\hypertarget{expected-findings}{%
\section{Expected findings}\label{expected-findings}}

In question 6: We expect the positive relationship between total data investment and GDP. Moreover we expect to see the steep line from 1900 to 2017.

In question 14: We expect the positive relationship between transportation (chained US dollar) and GDP (chained US dollar), the result can explain by the linear model and high effect value to GDP.

In question 18: We expect a strong relationship between GDP and federal investment, and both relations are positive linear relationships.

In question 20: We expect there is a positive linear relationship between GDP and total basic. infrastructure investment.

\hypertarget{analysis-and-findings}{%
\section{Analysis and findings}\label{analysis-and-findings}}

\textbf{Methodology}

This study uses the linear model to analysis because linear models are the simple and present a mathematical equation which easy to interpret and can be predictions. Moreover, the linear regression model is a reliable predictors because it is a long established statistical procedure and the character of linear regression is easy to understand (IBM, 2022).

\textbf{What is the relationship between total digital investment and GDP?}

\begin{figure}

{\centering \includegraphics{index_files/figure-latex/q6fig1-1} 

}

\caption{<center>The trend of total digital infrastructure investment from 1947 to 2017</center>}\label{fig:q6fig1}
\end{figure}

\begin{figure}
\centering
\includegraphics{index_files/figure-latex/q6fig2-1.pdf}
\caption{\label{fig:q6fig2}The trend of Gross Domestic Product (GDP) from 1947 to 2017}
\end{figure}

\begin{figure}
\centering
\includegraphics{index_files/figure-latex/q6fig3-1.pdf}
\caption{\label{fig:q6fig3}The relationship between total digital investment and gdp}
\end{figure}

\begin{table}
\centering
\begin{tabular}{l|r|r|r|r}
\hline
term & estimate & std.error & statistic & p.value\\
\hline
(Intercept) & 659595.9744 & 1.998196e+05 & 3.300957 & 0.0015277\\
\hline
digital & 112.6322 & 2.929285e+00 & 38.450403 & 0.0000000\\
\hline
\end{tabular}
\end{table}

\begin{table}
\centering
\begin{tabular}{r|r|r|r|r|r|r|r|r|r|r|r}
\hline
r.squared & adj.r.squared & sigma & statistic & p.value & df & logLik & AIC & BIC & deviance & df.residual & nobs\\
\hline
0.95541 & 0.9547638 & 1254559 & 1478.434 & 0 & 1 & -1096.733 & 2199.466 & 2206.254 & 1.086003e+14 & 69 & 71\\
\hline
\end{tabular}
\end{table}

Figure \ref{fig:q6fig1} shows the positive trend of total digital infrastructure investment, moreover, it is a steeply increasing trend between 1990 and 2017. Although overall the trend is an increasing trend, around 1999 to 2009 are a slight fluctuation. Figure \ref{fig:q6fig3} illustrates the proportion increasing between Total digital infrastructure and GDP is 1:1.

The table of results can be expressed in the formula as:

\[
\begin{align*}
{GDP} = 659595.97 + 112.63{digital}
\end{align*}
\]

This formula means if total digital infrastructure increases by 1 million US dollars, the Gross Domestic Product will increase by 112.63 million US dollars. This result is related to the study of Zhang et al.~(2022) that investigated the increase of digital economy will increase the GDP by around 0.78\%. Furthermore, they told it can be seen by the development of new technology such as the internet and mobile phone communication. R-squared is 95.54\% of the variance and it shows a nice linear model. Therefore, the result of a relationship between total digital infrastructure and GDP can be summarised by the linear model.

In Addition, this result same as our expected finding which is a positive relationship between total digital infrastructure and GDP. However, the trend of Total digital infrastructure has steeply increased since 1990, and GDP has steeply increased since 1980. It means total digital infrastructure doesn't significantly affect GDP from 1980 to 1990.

\textbf{What is the relationship between transportation investment (chained US dollars) and GDP (chained US dollars)?}

\begin{figure}
\centering
\includegraphics{index_files/figure-latex/q14fig4-1.pdf}
\caption{\label{fig:q14fig4}The trend of transpotation investment and Gross Domestic Product (GDP) from 1947 to 2017}
\end{figure}

\begin{figure}
\centering
\includegraphics{index_files/figure-latex/q14fig5-1.pdf}
\caption{\label{fig:q14fig5}The relationship between transportation investment and gdp}
\end{figure}

\begin{table}
\centering
\begin{tabular}{l|r|r|r|r}
\hline
term & estimate & std.error & statistic & p.value\\
\hline
(Intercept) & -5164.8342269 & 1185.5828124 & -4.356367 & 4.5e-05\\
\hline
Transportation & 0.1333108 & 0.0111639 & 11.941235 & 0.0e+00\\
\hline
\end{tabular}
\end{table}

\begin{table}
\centering
\begin{tabular}{r|r|r|r|r|r|r|r|r|r|r|r}
\hline
r.squared & adj.r.squared & sigma & statistic & p.value & df & logLik & AIC & BIC & deviance & df.residual & nobs\\
\hline
0.6739024 & 0.6691764 & 2852.588 & 142.5931 & 0 & 1 & -664.605 & 1335.21 & 1341.998 & 561470681 & 69 & 71\\
\hline
\end{tabular}
\end{table}

Figure \ref{fig:q14fig4} shows the positive trend of transportation investment (chained dollar), however, it is a steeply slight fluctuation between 1968 and 1998. While Gross Domestic Product (chained dollar) is a positive trend and increases over the year. Figure \ref{fig:q14fig5} illustrates the relationship between transportation investment (chained dollar) and GDP (chained dollar), nonetheless, it is difficult to explain the relationship between both variables as linear.

The table of results can be expressed in the formula as:

\[
\begin{align*}
{GDP} = -5164.83 + 0.13{Transportation}
\end{align*}
\]

This formula means if transportation investment increases by 1 million chained US dollars, the Gross Domestic Product will increase by 0.13 million chained US dollars. This result relates to the study of Weisbrod and Reno (2009) that argued the positive significance of the relationship between transportation investment and GDP. Moreover, transportation investment has a positive effect on economic growth (Lin, 2020). R-squared is 67.39\% of the variance. Therefore, the result of the relationship between transportation investment (chained dollar) and Gross Domestic Product (chained dollar) should not summary by a linear model, or this formula has omitted variables.

This result same as our expected finding that is a positive relationship between transportation investment (chained dollar) and Gross Domestic Product (chained dollar). However, this relationship can not explain by the linear model and the coefficient is too low which is not the same as our expected finding.

\textbf{What is the relationship between GDP and private investment, federal investment？And which one is stronger impact on GDP?}

\begin{figure}
\centering
\includegraphics{index_files/figure-latex/q18fig6-1.pdf}
\caption{\label{fig:q18fig6}The trends of private, federal investment and current GDP}
\end{figure}

\begin{figure}
\centering
\includegraphics{index_files/figure-latex/q18fig7-1.pdf}
\caption{\label{fig:q18fig7}The relationship between investment and GDP}
\end{figure}

Figure \ref{fig:q18fig6} illustrates the current GDP has a generally increasing trend over time, and the trend of gross private investment is similar to that. While the gross federal investment has fluctuated since around 1980 Figure 9.

By observing the trends of the three variables, this study predicts the current GDP and the other two might have a linear relationship, then we use a linear model to judge whether they have a linear relationship. As a result, GDP does have a linear relationship with private investment and federal investment respectively, and private investment has a stronger impact on current GDP.

R-squared is an important statistical measure that represents the proportion of the variance for current GDP that is explained by the gross private and federal investment in the regression model. For example, Figure \ref{fig:q18fig7} shows that 98.6\% of private investment can explain the current GDP, rather only 78.1\% of federal investment can explain that. Obviously, there is a stronger linear relationship between GDP and private investment which is unexpected. This result relates to the study of Private investment as the engine of economic growth and social welfare that investigated the private investment can explain the variance of GDP growth rate more than public investment (Doménech \& Sicilia, 2021).

Therefore, this results same as our expected finding that is the relationship between both variable and GDP is a linear model. However, the R-squared of federal investment is not as expected finding because the R-squared of private investment is much more valuable.

\textbf{Is there a linear relationship between GDP and total basic infrastructure investment? Positive or negative?}

\begin{table}
\centering
\begin{tabular}{l|r|r|r|r}
\hline
term & estimate & std.error & statistic & p.value\\
\hline
(Intercept) & -337073.45 & 117823.9903 & -2.861 & 0.0056\\
\hline
gross\_inv & 59.02 & 0.8235 & 71.672 & 0.0000\\
\hline
\end{tabular}
\end{table}

\begin{table}
\centering
\begin{tabular}{r|r|r|r|r|r|r|r|r|r|r|r}
\hline
r.squared & adj.r.squared & sigma & statistic & p.value & df & logLik & AIC & BIC & deviance & df.residual & nobs\\
\hline
0.9867 & 0.9866 & 683988 & 5137 & 0 & 1 & -1054 & 2113 & 2120 & 32280928200607 & 69 & 71\\
\hline
\end{tabular}
\end{table}

\begin{figure}
\centering
\includegraphics{index_files/figure-latex/q20fig8-1.pdf}
\caption{\label{fig:q20fig8}The relationship between GDP and total basic infrastructure investment}
\end{figure}

From the result can be expressed the formula as:

\[
\begin{align*}
{GDP} = -337073.45   + 59.02 {Basic}
\end{align*}
\]

This formula means if transportation investment increases by 1 million US dollars, the Gross Domestic Product will increase by 59.02 million US dollars. Moreover, the distribution of data has a positive linear relationship in figure \ref{fig:q20fig8}. The trend is increasing because the infrastructure investment effect increases a huge stock of public capital such as developing or creating new roads. That is a direct effect to increase government spending (G) in the GDP formula (Stupak, 2017). Furthermore, Gunnion (2021) claims that investment in infrastructure is a positive impact on economic output. R-squared is 98.67\% of the variance, therefore, the result of the relationship between total basic infrastructure investment and Gross Domestic Product can summary by the linear model.

Additionally, these results can confirm the expected finding is correct by the graph, the result of regression, and R-square.

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

This study explores infrastructural investment data in the USA and includes 4 interesting questions about the relationship between different categories of infrastructural investment and GDP. This study investigates the relationship between the total digital investment and GDP as a positive linear. Moreover, the correlative implication between transportation investment (chained US dollars) and GDP (chained US dollars) is a positive linear relationship. Furthermore, each association of private investment, federal investment, and GDP is a positive linear relationship and private investment is a higher effect on GDP than federal investment. In addition, total basic infrastructure investment has a positive linear relationship with GDP. In conclusion, the investment the study includes with GDP is all positive linear relationship, but different investments have different degrees of impact on GDP.

\hypertarget{references}{%
\section{References}\label{references}}

Auguie B (2017). \emph{gridExtra: Miscellaneous Functions for ``Grid'' Graphics}. R package
version 2.3, \url{https://CRAN.R-project.org/package=gridExtra}.

Doménech, R., \& Sicilia, J. (2021). Private investment as the engine of economic growth and social welfare / Private investment as the engine of economic growth and social welfare. \url{https://www.bbvaresearch.com/wp-content/uploads/2021/04/EWPrivate_Investment_and_GDP_growthWB.pdf}

Garrett Grolemund, Hadley Wickham (2011). Dates and Times Made Easy with lubridate.
Journal of Statistical Software, 40(3), 1-25. URL \url{https://www.jstatsoft.org/v40/i03/}.

Gunnion, L. (2021, July). What does infrastructure investment mean for the US economy? Deloitte Insights. \url{https://www2.deloitte.com/us/en/insights/economy/spotlight/impact-of-us-infrastructure-investment.html}

H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2016.

IBM. (2022). About Linear Regression \textbar{} IBM. Www.ibm.com. \url{https://www.ibm.com/topics/linear-regression}

Lin, X. (2020). Multiple pathways of transportation investment to promote economic growth in China: a structural equation modeling perspective. Transportation Letters, 12(7), 471--482. \url{https://doi.org/10.1080/19427867.2019.1635780}

Pebesma, E., 2018. Simple Features for R: Standardized Support for Spatial Vector Data.
The R Journal 10 (1), 439-446, \url{https://doi.org/10.32614/RJ-2018-009}

Robinson D, Hayes A, Couch S (2022). \emph{broom: Convert Statistical Objects into Tidy
Tibbles}. R package version 1.0.0, \url{https://CRAN.R-project.org/package=broom}.

Stupak, J. (2017). Economic Impact of Infrastructure Investment. \url{https://ecommons.cornell.edu/bitstream/handle/1813/78289/CRS_Economic_Impact_of_Infrastructure_Investment_0717.pdf?sequence=1\&isAllowed=y}

Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A,
Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K, Ooms J, Robinson
D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani H (2019). ``Welcome
to the tidyverse.'' \emph{Journal of Open Source Software}, \emph{4}(43), 1686.
\url{doi:10.21105/joss.01686} \url{https://doi.org/10.21105/joss.01686}.

Wickham H, Bryan J (2022). \emph{readxl: Read Excel Files}. R package version 1.4.0,
\url{https://CRAN.R-project.org/package=readxl}.

Weisbrod, G., \& Reno, A. (2009). ECONOMIC IMPACT OF PUBLIC TRANSPORTATION INVESTMENT. \url{https://onlinepubs.trb.org/onlinepubs/tcrp/docs/TCRPJ-11Task7-FR.pdf}

Yihui Xie (2022). knitr: A General-Purpose Package for Dynamic Report Generation in R. R
package version 1.39.

Zhang, J., Zhao, W., Cheng, B., Li, A., Wang, Y., Yang, N., \& Tian, Y. (2022). The Impact of Digital Economy on the Economic Growth and the Development Strategies in the post-COVID-19 Era: Evidence From Countries Along the ``Belt and Road.'' Frontiers in Public Health, 10. \url{https://doi.org/10.3389/fpubh.2022.856142}

Zhu H (2021). \emph{kableExtra: Construct Complex Table with `kable' and Pipe Syntax}. R
package version 1.3.4, \url{https://CRAN.R-project.org/package=kableExtra}.

Session information

\begin{verbatim}
## - Session info ---------------------------------------------------------------
##  setting  value
##  version  R version 4.1.2 (2021-11-01)
##  os       macOS Big Sur 10.16
##  system   x86_64, darwin17.0
##  ui       X11
##  language (EN)
##  collate  en_US.UTF-8
##  ctype    en_US.UTF-8
##  tz       Australia/Melbourne
##  date     2022-08-26
##  pandoc   2.18 @ /Applications/RStudio.app/Contents/MacOS/quarto/bin/tools/ (via rmarkdown)
## 
## - Packages -------------------------------------------------------------------
##  package       * version date (UTC) lib source
##  assertthat      0.2.1   2019-03-21 [1] CRAN (R 4.1.0)
##  backports       1.4.1   2021-12-13 [1] CRAN (R 4.1.0)
##  bit             4.0.4   2020-08-04 [1] CRAN (R 4.1.0)
##  bit64           4.0.5   2020-08-30 [1] CRAN (R 4.1.0)
##  bookdown      * 0.28    2022-08-09 [1] CRAN (R 4.1.2)
##  broom         * 1.0.0   2022-07-01 [1] CRAN (R 4.1.2)
##  cellranger      1.1.0   2016-07-27 [1] CRAN (R 4.1.0)
##  class           7.3-20  2022-01-13 [1] CRAN (R 4.1.2)
##  classInt        0.4-7   2022-06-10 [1] CRAN (R 4.1.2)
##  cli             3.3.0   2022-04-25 [1] CRAN (R 4.1.2)
##  colorspace      2.0-3   2022-02-21 [1] CRAN (R 4.1.2)
##  crayon          1.5.1   2022-03-26 [1] CRAN (R 4.1.2)
##  curl            4.3.2   2021-06-23 [1] CRAN (R 4.1.0)
##  DBI             1.1.3   2022-06-18 [1] CRAN (R 4.1.2)
##  dbplyr          2.2.1   2022-06-27 [1] CRAN (R 4.1.2)
##  digest          0.6.29  2021-12-01 [1] CRAN (R 4.1.0)
##  dplyr         * 1.0.9   2022-04-28 [1] CRAN (R 4.1.2)
##  e1071           1.7-11  2022-06-07 [1] CRAN (R 4.1.2)
##  ellipsis        0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
##  evaluate        0.16    2022-08-09 [1] CRAN (R 4.1.2)
##  fansi           1.0.3   2022-03-24 [1] CRAN (R 4.1.2)
##  farver          2.1.1   2022-07-06 [1] CRAN (R 4.1.2)
##  fastmap         1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
##  forcats       * 0.5.2   2022-08-19 [1] CRAN (R 4.1.2)
##  fs              1.5.2   2021-12-08 [1] CRAN (R 4.1.0)
##  gargle          1.2.0   2021-07-02 [1] CRAN (R 4.1.0)
##  generics        0.1.3   2022-07-05 [1] CRAN (R 4.1.2)
##  ggplot2       * 3.3.6   2022-05-03 [1] CRAN (R 4.1.2)
##  glue            1.6.2   2022-02-24 [1] CRAN (R 4.1.2)
##  googledrive     2.0.0   2021-07-08 [1] CRAN (R 4.1.0)
##  googlesheets4   1.0.1   2022-08-13 [1] CRAN (R 4.1.2)
##  gridExtra     * 2.3     2017-09-09 [1] CRAN (R 4.1.0)
##  gtable          0.3.0   2019-03-25 [1] CRAN (R 4.1.0)
##  haven           2.5.1   2022-08-22 [1] CRAN (R 4.1.2)
##  highr           0.9     2021-04-16 [1] CRAN (R 4.1.0)
##  hms             1.1.2   2022-08-19 [1] CRAN (R 4.1.2)
##  htmltools       0.5.3   2022-07-18 [1] CRAN (R 4.1.2)
##  httr            1.4.4   2022-08-17 [1] CRAN (R 4.1.2)
##  jsonlite        1.8.0   2022-02-22 [1] CRAN (R 4.1.2)
##  kableExtra    * 1.3.4   2021-02-20 [1] CRAN (R 4.1.2)
##  KernSmooth      2.23-20 2021-05-03 [1] CRAN (R 4.1.2)
##  knitr         * 1.40    2022-08-24 [1] CRAN (R 4.1.2)
##  labeling        0.4.2   2020-10-20 [1] CRAN (R 4.1.0)
##  lattice         0.20-45 2021-09-22 [1] CRAN (R 4.1.2)
##  lifecycle       1.0.1   2021-09-24 [1] CRAN (R 4.1.0)
##  lubridate     * 1.8.0   2021-10-07 [1] CRAN (R 4.1.0)
##  magrittr        2.0.3   2022-03-30 [1] CRAN (R 4.1.2)
##  Matrix          1.4-1   2022-03-23 [1] CRAN (R 4.1.2)
##  mgcv            1.8-40  2022-03-29 [1] CRAN (R 4.1.2)
##  modelr          0.1.9   2022-08-19 [1] CRAN (R 4.1.2)
##  munsell         0.5.0   2018-06-12 [1] CRAN (R 4.1.0)
##  nlme            3.1-159 2022-08-09 [1] CRAN (R 4.1.2)
##  pillar          1.8.1   2022-08-19 [1] CRAN (R 4.1.2)
##  pkgconfig       2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
##  proxy           0.4-27  2022-06-09 [1] CRAN (R 4.1.2)
##  purrr         * 0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
##  R6              2.5.1   2021-08-19 [1] CRAN (R 4.1.0)
##  Rcpp            1.0.9   2022-07-08 [1] CRAN (R 4.1.2)
##  readr         * 2.1.2   2022-01-30 [1] CRAN (R 4.1.2)
##  readxl        * 1.4.1   2022-08-17 [1] CRAN (R 4.1.2)
##  rematch         1.0.1   2016-04-21 [1] CRAN (R 4.1.0)
##  reprex          2.0.2   2022-08-17 [1] CRAN (R 4.1.2)
##  rlang           1.0.4   2022-07-12 [1] CRAN (R 4.1.2)
##  rmarkdown       2.16    2022-08-24 [1] CRAN (R 4.1.2)
##  rstudioapi      0.14    2022-08-22 [1] CRAN (R 4.1.2)
##  rvest           1.0.3   2022-08-19 [1] CRAN (R 4.1.2)
##  scales          1.2.1   2022-08-20 [1] CRAN (R 4.1.2)
##  sessioninfo     1.2.2   2021-12-06 [1] CRAN (R 4.1.0)
##  sf            * 1.0-8   2022-07-14 [1] CRAN (R 4.1.2)
##  stringi         1.7.8   2022-07-11 [1] CRAN (R 4.1.2)
##  stringr       * 1.4.1   2022-08-20 [1] CRAN (R 4.1.2)
##  svglite         2.1.0   2022-02-03 [1] CRAN (R 4.1.2)
##  systemfonts     1.0.4   2022-02-11 [1] CRAN (R 4.1.2)
##  tibble        * 3.1.8   2022-07-22 [1] CRAN (R 4.1.2)
##  tidyr         * 1.2.0   2022-02-01 [1] CRAN (R 4.1.2)
##  tidyselect      1.1.2   2022-02-21 [1] CRAN (R 4.1.2)
##  tidyverse     * 1.3.2   2022-07-18 [1] CRAN (R 4.1.2)
##  tinytex       * 0.41    2022-08-16 [1] CRAN (R 4.1.2)
##  tzdb            0.3.0   2022-03-28 [1] CRAN (R 4.1.2)
##  units           0.8-0   2022-02-05 [1] CRAN (R 4.1.2)
##  utf8            1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
##  vctrs           0.4.1   2022-04-13 [1] CRAN (R 4.1.2)
##  viridisLite     0.4.1   2022-08-22 [1] CRAN (R 4.1.2)
##  vroom           1.5.7   2021-11-30 [1] CRAN (R 4.1.0)
##  webshot         0.5.3   2022-04-14 [1] CRAN (R 4.1.2)
##  withr           2.5.0   2022-03-03 [1] CRAN (R 4.1.2)
##  xfun            0.32    2022-08-10 [1] CRAN (R 4.1.2)
##  xml2            1.3.3   2021-11-30 [1] CRAN (R 4.1.0)
##  yaml            2.3.5   2022-02-21 [1] CRAN (R 4.1.2)
## 
##  [1] /Library/Frameworks/R.framework/Versions/4.1/Resources/library
## 
## ------------------------------------------------------------------------------
\end{verbatim}

\end{document}
